services:

  paymybuddy-db:
    image: kingsley95/mini-projet-docker:paymybuddy-db
    container_name: paymybuddy-db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - paymybuddy-data:/var/lib/mysql
      - ./initdb/create.sql:/docker-entrypoint-initdb.d/create.sql:ro
    networks:
      - paymybuddy-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  paymybuddy-backend:
    image: kingsley95/mini-projet-docker:paymybuddy-app
    container_name: paymybuddy-backend
    depends_on:
      paymybuddy-db:
        condition: service_healthy
        
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - paymybuddy-network
    ports:
      - "8080:8080"

volumes:
  paymybuddy-data:

networks:
  paymybuddy-network: